# This rule is not used by the project test-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to test.olm.operatorframework.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: test-operator
    app.kubernetes.io/managed-by: kustomize
  name: olmtest-viewer-role
rules:
- apiGroups:
  - test.olm.operatorframework.io
  resources:
  - olmtests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.olm.operatorframework.io
  resources:
  - olmtests/status
  verbs:
  - get
