---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - test.olm.operatorframework.io
  resources:
  - olmtests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.olm.operatorframework.io
  resources:
  - olmtests/finalizers
  verbs:
  - update
- apiGroups:
  - test.olm.operatorframework.io
  resources:
  - olmtests/status
  verbs:
  - get
  - patch
  - update
